using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Assets.HotFix.MyUtils.src.data;
using Assets.HotFix.xq2d.src.ui.part;
using Newtonsoft.Json.Linq;

namespace Assets.HotFix.xq2d.src.common
{
    class msgCode
    {
        public static void showMsg(int code, object param = null)
        {
            //textTipUI.getInstance().setText(getStrByCode(code, param));
            MsgSureUI.create(PointGet.getTipCanvas()).hideBtn().setMaskAlpha(0).renderText(getStrByCode(code, param));
            DoGet.getInstance().startReqImg();
        }
        public static string getStrByCode(int code, object param = null)
        {
            switch (code)
            {
                case -2: return "操作频繁！";
                

                case 200: return "成功！";
                case 201: return ""+param;
                case 202: return "金额超出最大值"+int.MaxValue+"，超出部分已被舍弃！";
                case 203: return "对方余额将超出最大值" + int.MaxValue + "，操作已被撤销！";
                case 204: return "自己上架的商品，无法进行购买！";
                case 205: return "商品数量不足，无法进行购买！";
                case 206: return "成长失败，超出最大资质，请重生或者洗资！";
                case 207: return "天生技能，不可遗忘！";
                case 208: return "此位置并没有技能！";
                case 209: return "不存在白装！";
                case 210: return "未达到指定数量！";
                case 211: return "无法再继续合成，请使用宠物强化！";
                case 212: return "vip等级不足，无法进行强化！";
                case 213: return "已经领取过了！";
                case 214: return "vip等级不足！";
                case 215: return "积分不足以领取下一档礼包！";
                case 216: return "请选择附件！";
                case 217: return "请设置正经数量！";
                case 218: return "道具已过期！";
                case 219: return "附件已过期！";
                case 220: return "宝箱已过期！";
                case 221: return "未报名帮战！";
                case 222: return "请清理邮件！";
                case 223: return "战斗中，禁止此类操作！";
                case 224: return "无法出战，超过人物等级10级或未达到出战等级！";
                case 225: return "无法使用材料兑换！";
                case 226: return "获得印象分"+ param;
                case 227: return "今日印象分已领取！当前总印象分：" + param;
                case 228: return "请先将回天书从仓库取出！";

                case 600: return "账号不存在！";
                case 601: return "账号密码有误！";
                case 602: return "角色不存在！";
                case 603: return "账号重复！";
                case 604: return "暂无更新！";
                case 605: return "角色名重复！";
                case 606: return "账号或密码长度至少6位,且只能为字母或数字！";
                case 607: return "注册成功，请前往登录！";
                case 608: return "没有足够技能槽！";
                case 609: return "今日答题已完成！";
                case 610: return "次数不足！";
                case 611: return "今日活动已完成！";
                case 612: return "任务已接取!";
                case 613: return "等级不足!";
                case 614: return "不是本门弟子!";
                case 615: return "无可学习的技能!";
                case 616: return "账号和密码6-12位字母、数字！不能出现中文和特殊符号！";
                case 617: return "请输入有效内容！";
                case 618: return "请输入1-6位中文、字母、数字！";
                case 619: return "别闹，又不是你的东西！";
                case 620: return "队长离你太远！";
                case 621: return "只有未出战的宠物才能放生哟！";
                case 622: return "放生成功！";
                case 623: return "玩家不接受切磋！";
                case 624: return "别闹！自己人！";
                case 625: return "技能已达到满级！";
                case 626: return "人数已满！";
                case 627: return "发言过于频繁！";
                case 628: return "宠物未出战！";
                case 629: return "使用成功！";
                case 630: return "不允许组队！";
                case 631: return "不能超过人物10级！";
                case 632: return "该玩家不允许切磋！";
                case 633: return "请先接取任务！";
                case 634: return "余额不足！";
                case 635: return "已经学习过了哟！";
                case 636: return "技能学习成功！";
                case 637: return "数量不足！";
                case 638: return "已有队伍！";
                case 639: return "使用失败！";
                case 640: return "背包已满！";
                case 641: return "不允许传送！";
                case 642: return "此类商品购买数量受限制！";
                case 643: return "玩家已经有帮派了！";
                case 644: return "帮派创建失败！";
                case 645: return "创建成功！";
                case 646: return "已提交申请！";
                case 647: return "请勿重复申请！";
                case 648: return "未加入帮派！";
                case 649: return "您没有权限哟！";
                case 650: return "对方已经有帮派或帮派人数已满！";
                case 651: return "存在未填入的数据！" + param;
                case 652: return "该物品不存在！";
                case 653: return "锻造成功！";
                case 654: return "锻造失败！装备损毁！";
                case 655: return "装备已经损毁，不可再进行锻造！";
                case 656: return "已达最大等级！";
                case 657: return "修复成功！";
                case 658: return "合成成功！";
                case 659: return "合成失败！";
                case 660: return "镶嵌孔不足，请先移除镶嵌石！";
                case 661: return "镶嵌成功！";
                case 662: return "注入成功！";
                case 663: return "该装备未注入潜力！";
                case 664: return "设置成功！";
                case 665: return "已取消！";
                case 666: return "报名成功！";
                case 667: return "已经报过名了！";
                case 668: return "很遗憾，已被其他玩家买走！";
                case 669: return "恭喜您抢购成功！该物品已放入背包。";
                case 670: return "请先组队！";
                case 671: return "名称重复了哟！";
                case 672: return "有队员不在线！";
                case 673: return "有队员已经报过名了！";
                case 674: return "报名时间已过！";
                case 675: return "暂未发布名单！";
                case 676: return "此地图不允许切磋！";
                case 677: return "已发送！";
                case 678: return "打孔成功！";
                case 679: return "请先绑定邮箱！";
                case 680: return "邮箱格式有误！";
                case 681: return "对方处于战斗中！";
                case 682: return "经验不足！";
                case 683: return "超过技能最大等级或技能书数量不足！";
                case 684: return "职业不符！";
                case 685: return "没有可开启的技能槽位！";
                case 686: return "扩展成功！";
                case 687: return "当前状态下不允许传壁哟！";
                case 688: return "开始传壁！";
                case 689: return "当前状态下不允许抢夺！";
                case 690: return "已上架！";
                case 691: return "上架失败！";
                case 692: return "购买成功！";
                case 693: return "购买失败！";
                case 694: return "世上竟有如此小气之人！";
                case 695: return "给个口令吧！";
                case 696: return "不在活动时间内！";
                case 697: return "下架失败！";
                case 698: return "在线时长不足！";
                case 699: return "领取成功！";
                case 700: return "投资成功！";
                case 701: return "请勿重复投资！";
                case 702: return "队伍不存在！";
                case 703: return "真元点数不足！";
                case 704: return "经脉提升成功！";
                case 705: return "已重置！";
                case 706: return "缺少道具！";
                case 707: return "请到邮箱查看验证码，可能在垃圾箱里面哟！";
                case 708: return "黑名单玩家！";
                case 709: return "为了账户安全，请先验证邮箱！";
                case 710: return "价格已经发生变动！";
                case 711: return "成功补刀！";
                case 712: return "恭喜抢下最后一刀！";
                case 713: return "等待结果！";
                case 714: return "请先完成试炼任务！";
                case 715: return "请勿重复报名！";
                case 716: return "此地图不允许偷袭！";
                case 717: return "技能已覆盖！";
                case 718: return "技能取消覆盖！";
                case 719: return "取消失败！";
                case 720: return "尚有任务在身（或已全部完成）！";
                case 721: return "请带着你的师傅来登记！";
                case 722: return "已递交申请！";
                case 723: return "不符合拜师条件！";
                case 724: return "逆徒，你要背叛师门吗！";
                case 725: return "对方弟子已满，你注定与他有缘无份了！";
                case 726: return "关系已解除！";
                case 727: return "关系无法解除！";
                case 728: return "看来今天不是个黄道吉日，不宜出师！";
                case 729: return "帮派boss未开启！";
                case 730: return "帮派boss已被击杀！";
                case 731: return "帮派boss未被击杀！";
                case 732: return "奖励已被土匪无情的夺走！";
                case 733: return "此情况之下，就算是胖虎也无能为力呀！";
                case 734: return "无法退出帮派！";
                case 735: return "操作成功！";
                case 736: return "无法接取！";
                case 737: return "打劫，把你的贞操交出来，或者拿10000元宝贿赂胖虎我！";
                case 738: return "该技能已遗忘！";
                case 739: return "精炼成功！";
                case 740: return "已达到最高等级！";
                case 741: return "该宠物不配被吞噬！";
                case 742: return "宠物需要突破！";
                case 743: return "宠物需要进化！";
                case 744: return "吞噬成功！";
                case 745: return "未达到突破条件！";
                case 746: return "未达到进化条件！";
                case 747: return "成功突破！";
                case 748: return "成功进化！";
                case 749: return "开始为帮派灵兽加血，为期1分钟！";
                case 750: return "本次帮战已失败！";
                case 751: return "正处于加血中！";
                case 752: return "灵兽不需要加血！";
                case 753: return "没有权限！";
                case 754: return "未报名！";
                case 755: return "报过名了！";
                case 756: return "队伍中有其他帮派成员！";
                case 757: return "不在活动时间内！";
                case 758: return "成功出售！";
                case 759: return "出售失败！";
                case 760: return "未完成10万营业额的目标！";
                case 761: return "未获得该称号！";
                case 762: return "成功改名！";
                case 763: return "改名失败！";
                case 764: return "宠物列表已满！";
                case 765: return "给你的任务完成了吗？";
                case 766: return "已完成，不可放弃！";
                case 767: return "玩家处于冷却期（8小时），暂时不能加入任何帮派！";
                case 768: return "无需重置！";
                case 769: return "对方没有处于战斗中！";
                case 770: return "没有该玩家！";
                case 771: return "你们已经是好友了！";
                case 772: return "好友数不能超过40个！";
                case 773: return "恭喜你们成为好友！";
                case 774: return "玩呢？";
                case 775: return "目标已刷新";
                case 776: return "有新版本，请重新进入游戏！";
                case 777: return "您的宠物由于太萌萌哒，导致无法习会该技能！";
                case 778: return "升金成功!";
                case 779: return "升金失败!";
                case 780: return "请先装备!";
                case 781: return "禁售商品!";
                case 782: return "未解锁!";
                case 783: return "已解锁!";
                case 784: return "已领取!";
                case 785: return "未在指定期限内!";
                case 786: return "附件数量不能超出3个!";
                case 787: return "已下架!";
                case 788: return "装备未镶嵌宝石!";
                case 789: return "装备的全部潜力已经开发完了!";
                case 790: return "装备是坏的，设置失败!";
                case 791: return "无可用的宝石!";
                case 792: return "当前没有玩家传壁!";
                case 793: return "离线状态，无法查看!";
                case 794: return "请让队长操作!";
                case 795: return "对方正在战斗!";
                case 796: return "不能低于"+param;
                case 797: return "网络波动，请重试!";
                case 798: return "帮派申请惨遭拒绝!";
                case 799: return "欢迎新成员 " + param + " 的加入，大伙快举双脚欢迎!";
                case 800: return "出价过低!";
                case 801: return "恭喜您为世界和平出了一份价!";
                case 802: return "为了世界和平有份心意就够了，谈钱多市侩!";
                case 803: return "玩家" + param + "发起了竞拍，两元两元，样样只要两元，买不了吃亏买不了上当！";
                case 804: return "您拍卖的商品有买家出价了，详情请看竞拍页";
                case 805: return "位置不足!";
                case 806: return "买家资金不足!";
                case 807: return "竞拍商品不存在!";
                case 808: return "小子，你的东东卖了个好价钱!";
                case 809: return "配置完成!";
                case 810: return "有队员未配置主副宠!";
                case 811: return "已发布!";
                case 812: return "投放悬赏至少100（或余额不足）!";
                case 813: return "就算人工智障也无法识别你的操作!";
                case 814: return "身上有追杀令尚未完成!";
                case 815: return "已被其他玩家接取!";
                case 816: return "对方不是你要追杀的对象!";
                case 817: return "属性点溢出!";
                case 818: return "每条分配的属性点不能低于5!";
                case 819: return "存在不可分配的技能!";
                case 820: return "技能不能重复!";
                case 821: return "主副宠物不能重复!";
                case 822: return "请带上你的师傅一起组队（师徒两人，队长徒弟）!";
                case 823: return "已同意!";
                case 824: return "恭喜你把师傅的饭碗给砸了!";
                case 825: return "等级不符!";
                case 826: return "每日限制吃10只!";
                case 827: return "属性溢出!";
                case 828: return "精炼石缺失!";
                case 829: return "副装备缺失!";
                case 830: return "仓库已满";
                case 831: return "对方已离线!";
                case 832: return "无法执行!";
                case 833: return "不满足使用条件!";
                case 834: return "无法发布!";
                case 835: return "感谢支持!";
                case 836: return "暂时不支持该货币!";
                case 837: return "请先清理背包!";
                case 838: return "兑换成功!";
                case 839: return "只能分解未锻造过的神装!";
                case 840: return "已经飞升!";
                case 841: return "此装备不能飞升!";
                case 842: return "需要先模板重铸!";
                case 843: return "请先升金!";
                case 844: return "已登记!";
                case 845: return "无可选择!";
                case 846: return "此装备不可进行该操作!";
                case 847: return "增幅成功!";
                case 848: return "增幅失败，强度-1!";
                case 849: return "剩余冷却时间" + param + "秒";
                case 850: return "结算中!";
                case 851: return "玩家不存在!";
                case 852: return "对方邮件已满!";
                case 853: return "有任务未完成!";
                case 854: return "次数不足!";
                case 855: return "活跃度需要达到" + param + "!";
                case 856: return "所需材料数量不足！需要" + param + "！";
                case 857: return "已点亮!";
                case 858: return "已达到极限!";
                case 859: return "已解锁坐骑!";
                case 860: return "恭喜获得宠物" + param + "!";
                case 861: return "请选择一项！";
                case 862: return "请到传壁场景！";
                case 863: return "活动未开启！";
                case 864: return "徒弟已达上限！";
                case 865: return "暂无登记的玩家，请稍后再试！";
                case 866: return "已登记！";
                case 867: return "请勿重复登记！";
                case 868: return "请带上你的徒弟吧！";
                case 869: return "请带上你的师傅吧！";
                case 870: return "需要徒弟、师傅组队！";
                case 871: return "该任务已完成！";
                case 872: return "请选择锻造宝石！";
                case 873: return "未开启技能槽位！";
                case 874: return "未学习技能！";
                case 875: return "背包中没有精炼宝石！";
                case 876: return "请勾选需要精炼的主装备属性！";
                case 877: return "请勾选需要被吃掉的副装备属性！";
                case 878: return "签到成功！";
                case 879: return "角色名不符合规范！";
                case 880: return "请选择投资类型！";
                case 881: return "请先完成任务！";
                case 882: return "已经开过了！";
                case 883: return "该场景禁止此类战斗！";
                case 884: return "匹配中！";
                case 885: return "消息过期了！";
                case 886: return "帮派不存在！";
                case 887: return "帮派建设度未满！";
                case 888: return "活动进行中，无需重复开启！";
                case 889: return "活动开启！";
                case 890: return "帮贡不足！";
                case 891: return "红包已被领完！";
                case 892:
                    return "抢到红包" + (((JObject)param)["money"]) +
                  (((int)((JObject)param)["moneyType"]) == 0 ? ("元宝") : ("银两")) + "！";
                case 893: return "所有强盗已被消灭！";
                case 894: return "该称号已经激活！";
                case 895: return "恭喜获得新称号！";
                case 896: return "穿戴成功！";
                case 897: return "脱下成功！";
                case 898: return "已激活！";
                case 899: return "已经达到当前等级最大出战人数！";
                case 900: return "装备品质不一致！";
                case 901: return "装备没有可精炼的属性！";
                case 902: return "最多10个架位！";
                case 903: return "正在疯狂抢购，请稍后。。。";
                case 904: return "恭喜秒杀到[" + param + "]";
                case 905: return "背包没有足够的空位！";
                case 906: return "请先完成觉醒！";
                case 907: return "已达到最大升星等级！";
                case 908: return "已达到最大升品等级！";
                case 909: return "请先转让帮主！";
                case 910: return "处于保护期！";
                case 911: return "魔神未刷新！";
                case 912: return "有玩家正在参与争夺！";
                case 913: return "境界不足！";
                case 914: return "未战胜心魔！";
                case 915: return "需要达到100级！";
                case 916: return "境界成功突破！";
                case 917: return "当前境界的心魔已经被您击败了！";
                case 918: return "该位置已经被使用！";
                case 919: return "请留些位置给其他人吧！";
                case 920: return "未成熟！";
                case 921: return "请不要偷菜哟！";
                case 922: return "已经成熟，可以收获！";
                case 923: return "未超过成熟期24小时，不允许铲除！";
                case 924: return "帮派等级不足！";
                case 925: return "伙伴已经激活过了！";
                case 926: return "缺少洪荒密钥（请到商城处购买）！";
                case 927: return "无法进入该场景！";
                case 928: return "资源包未发现，请到qq群文件上下载！";
                case 929: return "请选择职业！";
                case 930: return "未加入分堂！";
                case 931: return "未击败魔神！";
                case 932: return param + "，满意度不足！";
                case 933: return "满意度(" + param + ")";
                case 934: return "已击败！";
                case 935: return "已达打孔上限！";
                case 936: return "道具不存在！";
                case 937: return "该装备无法精炼！";
                case 938: return "装备不允许出现同名属性！";
                case 939: return "不在范围内！";
                case 940: return "超出品质范围！";
                case 941: return "锻造等级不足！";
                case 942: return "装备等级不足！";
                case 943: return "该部位无法进行提升抗性！";
                case 944: return "模板与装备的职业、部位不符！";
                case 945: return "已经满了！";
                case 946: return "已经血契过了！";
                case 947: return "该装备未刻印！";
                case 948: return "提升失败！";
                case 949: return "因回天书使用超时未确认，该操作已由系统完成！";
                case 950: return "今日已经炼制过了！";
                case 951: return "炼制失败，获得60点声望！";
                case 952: return "炼化成功，获得" + param + "点声望！";
                case 953: return "请先装备法宝！";
                case 954: return "强化失败！";
                case 955: return "没有剩余注灵次数！";
                case 956: return "输入有误！";
                case 957: return "成长度增加" + param;
                case 958: return "成长等级提升1级";
                case 959: return "超过最大使用数量";
                case 960: return "已达最低属性转出";
                case 961: return "此丹已经无法再提升悟性了";
                case 962: return "悟性提升" + param + "点";
                case 963: return "悟性不足";
                case 964: return "获得人气值" + param;
                case 965: return "建设度增加" + param + "，帮派总贡献增加" + param + "，个人贡献增加" + param;
                case 966: return "该建设度已满！";
                case 967: return "帮派资金增加" + param;
                case 968: return "最低捐献1000银两";
                case 969: return "建设度不足！";
                case 970: return "建设金不足！";
                case 971: return "猴子已经被全部赶走！";
                case 972: return "已经加入过门派了！";
                case 973: return "成功加入门派！";
                case 974: return "已经加入过分堂了！";
                case 975: return "成功加入分堂！";
                case 976: return "未加入门派！";
                case 977: return "未获得！";
                case 978: return "请先完成突破任务！";
                case 979: return "此技能暂未上线，请期待后续更新！";
                case 980: return "付费邮件需退回";
                case 981: return "宠物禁止逃跑";
                case 982: return "技能冷却中！";
                case 983: return "对不起，您猜错了！";
                case 984: return "获得经验"+param;
                case 985: return "本次聚灵已结束！";
                case 986: return "开始聚灵！";
                case 987: return "请先前往宠物乐园再使用！";
                case 988: return "已达最大扩容数！";
                case 989: return "超过最大存储银两！当前等级能存储的最大银两为："+param;
                case 990: return "需要搜寻到3把钥匙才能进入下一层！";
                case 991: return "箱子被开启！";
                case 992: return "需要清除10次怪物才能进入下一层！";
                case 993: return "有队员未跟随！";
                case 994: return "有队员缺少开启活动的道具！";
                case 995: return "恭喜获得道具！";
                case 996: return "自动遇怪已取消！";
                case 997: return "帮派等级不足，无法开启活动！";
                case 998: return "跑商任务尚未完成！";
                case 999: return "跑商任务已完成，恭喜获得40000银两！";

                case 1000: return "格式为6-12位字母、数字！";
                case 1001: return "登陆中！";
                case 1002: return "数据有误！";
                case 1003: return "请先绑定邮箱！";
                case 1004: return "黑名单玩家！";
                case 1005: return "为了账户安全，请先验证邮箱！";
                case 1006: return "账号密码有误！";
                case 1007: return "有新版本，请重新进入游戏！";
                case 1008: return "登录成功！";
                case 1009: return "网络错误，登录失败！";
                case 1010: return "载入玩家信息！";
                case 1011: return "进入场景！";

                case 1012: return "需要服用更高级的丹药提升您的真元点！";
                case 1013: return "获得"+param+"点人气值！";
                case 1014: return "已经有师傅了！";
                case 1015: return "您与任何人都没有关系！";
                case 1016: return "没有任务！";
                case 1017: return "没有任何可被通缉的对象！";
                case 1018: return "非指定目标！";
                case 1019: return "禁止捕捉！";
                case 1020: return "偷得太过分了，给人留点吧！";
                case 1021: return "任务已刷新，请重新接取！";
                case 1022: return "职位已满！";
                case 1023: return "该道具不允许直接使用！";
                case 1024: return "请先加入分堂！";
                case 1025: return "该礼物已经领过了！";
                case 1026: return "跟随中队长中，无法移动！";

                default:
                    {
                        return "服务器忙！";
                    }
            }
        }
    }
}
